[project]
name = "mini-mind"
version = "0.1.0"
description = "stan 的 minimind学习"
readme = "README.md"
authors = [
    { name = "neystan", email = "2918360904@qq.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "torch>=2.9.0",
    "transformers>=4.57.1",
]

[project.scripts]
mini-mind = "mini_mind:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
